version: '3.8'

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - db
      - redis
  # frontend:
  #   build:
  #     context: frontend
  #     dockerfile: Dockerfile
  #     args:
  #       VITE_API_URL: http://194.135.25.94:3000
  #   environment:
  #     - VITE_API_URL=http://194.135.25.94:3000
  #   container_name: frontend
  #   restart: always
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   ports:
  #     - "3666:80"
  #   depends_on:
  #     - backend
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    restart: unless-stopped
volumes:
  postgres_data:
networks:
  default:
    name: app-network