version: '3.8'

services:
  # frontend:
  #   build:
  #     context: frontend
  #     dockerfile: Dockerfile
  #     args:
  #       VITE_API_URL: db
  #   environment:
  #     - VITE_API_URL=db
  #   container_name: frontend
  #   restart: always
  #   ports:
  #     - "3666:80"
  #   depends_on:
  #     - backend
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 5
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    restart: unless-stopped
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      db: 
        condition: service_healthy
      redis:
        condition: service_started
    env_file: .env
volumes:
  postgres_data:
